name: Docker Build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 23 * * *' # Auto build Docker at 23.00 every day
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKER }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ secrets.TAGS }}
        
    - name: send telegram message
      run: |
          function sendTG() {
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendmessage" --data "text=${*}&chat_id=${{ secrets.TELEGRAM_TO }}&parse_mode=Markdown"
          }
          sendTG "\`I have pushed new images to docker\` %0A ${{ secrets.LINK2 }}" &> /dev/null
